#!/bin/sh
printf 'LABEL=IGLU_ROOT	/		ext4	defaults	0	0\n' > /mnt/new-root/etc/fstab
printf 'LABEL=IGLU_BOOT	/boot	vfat	defaults	0	0\n' >> /mnt/new-root/etc/fstab

printf 'Adding root user\n'
cat > /mnt/new-root/etc/passwd << EOF
root:x:0:0:Admin,,,:/root:/bin/sh
EOF

cat > /mnt/new-root/etc/group << EOF
root:x:0:
EOF

cat > /mnt/new-root/etc/shadow << EOF
root::::::::
EOF

chmod 600 /mnt/new-root/etc/shadow

printf 'Set root password\n'

chroot /mnt/new-root /bin/busybox passwd

printf 'Generating initrd\n'
mkdir -p /mnt/new-root/tmp
mount --bind /tmp /mnt/new-root/tmp
chroot /mnt/new-root /sbin/mkrd

printf 'Installation should now be finished!\n'
printf 'Chroot into your new system to inspect everything before rebooting\n'
